### ISSUE TITLE
Errors building

### ISSUE THREAD

**Issue by mikeymckay** [pouchdb/pouchdb-fauxton-base#1]
I'm having some troubles building. Below is what I see:

crazy@shoshone /var/www/pouchdb-fauxton-base npm install
npm WARN package.json couchapp@0.11.0 No repository field.
npm WARN package.json url@0.7.9 No README data
npm WARN package.json urls@0.0.4 No repository field.
npm WARN unmet dependency /var/www/pouchdb-fauxton-base/node_modules/grunt-contrib-less/node_modules/chalk requires ansi-styles@'^1.1.0' but will load
npm WARN unmet dependency /var/www/pouchdb-fauxton-base/node_modules/ansi-styles,
npm WARN unmet dependency which is version 2.0.0
npm WARN unmet dependency /var/www/pouchdb-fauxton-base/node_modules/grunt-contrib-less/node_modules/maxmin requires chalk@'^0.4.0' but will load
npm WARN unmet dependency /var/www/pouchdb-fauxton-base/node_modules/grunt-contrib-less/node_modules/chalk,
npm WARN unmet dependency which is version 0.5.1
crazy@shoshone /var/www/pouchdb-fauxton-base ./bin/grunt couchdb
Loading "less.js" tasks...ERROR

> > Error: Cannot find module 'strip-ansi'

Running "clean:release" (clean) task
Cleaning "app/load_addons.js"...OK

Running "clean:watch" (clean) task

Running "get_deps:default" (get_deps) task
Fetching external dependencies
0 remote dependencies
0 local dependencies

Running "gen_load_addons:default" (gen_load_addons) task

Running "gen_initialize:release" (gen_initialize) task

Running "jshint:all" (jshint) task

> > 98 files lint free.
> > Warning: Task "less" not found. Use --force to continue.

Aborted due to warnings.

**Comment by marten-de-vries** [comment]
So this is an error in Fauxton's build process, of which I know barely anything. Most likely it just broke one day when someone didn't keep semver in mind while updating some npm package. So my only advice is to try and work around it, e.g.:
`npm install strip-ansi`

Also, you could use a prebuild version as available here: https://github.com/marten-de-vries/pouchdb-fauxton-logic/tree/master/fauxton

**Comment by marten-de-vries** [comment]
I just updated the branch with a largely rewritten Fauxton. Going to close this.
